<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Customer\Block\Newsletter       $newsLetterBlock
 */

$newsLetterBlock = $block->getParentBlock();
/* @var \Magento\Customer\Model\Data\Customer $customer */
$customer = $newsLetterBlock->getCustomer();

/* @var \Magento\Framework\Api\AttributeValue $valuePostalMailings */
$postalMailings = $customer->getCustomAttribute(CoxAndCox\MarketingPreferences\Api\MarketingPreferences::POSTAL_MAILINGS_ATTR_CODE);
/* @var \Magento\Framework\Api\AttributeValue $valueThirdParty */
$thirdParty = $customer->getCustomAttribute(CoxAndCox\MarketingPreferences\Api\MarketingPreferences::THIRD_PARTY_ATTR_CODE);

$valuePostalMailings = 0;
if ($postalMailings) {
    $valuePostalMailings = $postalMailings->getValue();
}

$valueThirdParty = 0;
if ($thirdParty) {
    $valueThirdParty = $thirdParty->getValue();
}

?>


<div class="field choice">
    <input type="checkbox" name="third_party" id="third-party" data-role="third-party" value="1" <?php if ((int)$valueThirdParty == 1): ?> checked="checked"<?php endif; ?> title="<?= $block->escapeHtml(__('Third Party')) ?>" class="checkbox" />
    <label class="label" for="change-email"><span><?= $block->escapeHtml(__('Third Party')) ?></span></label>
</div>

<div class="field choice">
    <input type="checkbox" name="postal_mailings" id="postal-mailings" data-role="postal-mailings" value="1" <?php if ((int)$valuePostalMailings == 1): ?> checked="checked"<?php endif; ?> title="<?= $block->escapeHtml(__('Postal Mailings')) ?>" class="checkbox" />
    <label class="label" for="change-email"><span><?= $block->escapeHtml(__('Postal Mailings')) ?></span></label>
</div>
